# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: WineStorage
version: "1.0.2"
slug: winestorageapi
description: WineStorage add-on
url: "https://github.com/marchorst/WineStorageHomeAssistantRepository"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
panel_icon: "mdi:bottle-wine"
map:
  - share:rw
ingress: true
ingress_port: 8080
#image: "ghcr.io/home-assistant/{arch}-addon-example"
